### ISSUE TITLE
Improvement for German Amazon

### ISSUE THREAD

**Issue by selimovd** [TristanH/bookcision#11]
Hello,

first of all thank you very much, this awesome tool! It helps me so much to download and order my highlights!
As I have an account on German Amazon I have a suggestion to improve the program. 

When I go to the German URL to read online (read.amazon.de) I will be forwarded to https://lesen.amazon.de what just means read.amazon.de. On this site the bookmarklet doesn't work. 
As a workaround I can go to read.amazon.com but I get the notice that I need a US Amazon account. Somehow it works anyway with my German credentials, so I'm fine. But I think it would be nice for the German audience (2nd biggest Amazon market after US) if it would also work with lesen.amazon.de.

Thank you and best regards

**Comment by TristanH** [comment]
Hey @selimovd can you try out the solution here?

https://github.com/TristanH/bookcision/issues/15#issuecomment-768002990

That url should actually work for all german users, assuming they set their language on amazon.com to english (but I'd be curious to know if that's ever not the case!) Thanks :)
