### ISSUE TITLE
Error message: "You have no highlights for this book yet."

### ISSUE THREAD

**Issue by MXMLLN** [TristanH/bookcision#12]
Bookcision recently stopped working for me. Ran the bookmarklet on https://read.amazon.com/notebook .

Anybody know why the script suddenly stopped working?

Thanks for the tool.

**Comment by TristanH** [comment]
Hia! It seems that read.amazon.com/notebook is actually down right now (try clicking any book cover), which is causing the issue.

We're doing our best to monitor the issue. It might help if you emailed Kindle's support and let them know that their page is broken!

**Comment by MXMLLN** [comment]
My mistake. I did refresh the page and check two different books before posting. Rechecking the site, it is much more clear that Amazon is down.
