### ISSUE TITLE
No highlights for book

### ISSUE THREAD

**Issue by mjremijan** [TristanH/bookcision#13]
Now when I use bookcision I get the message "You have no highlights for this book yet."

I definitely have highlights and notes.

I don't have any other info other than it was working and now it's not. Also I've been using it with Chrome.

**Comment by TristanH** [comment]
Hey Michael, see #12 

It seems that https://read.amazon.com/notebook is actually down right now (try clicking any book cover), which is causing the issue.

We're doing our best to monitor the issue. It might help if you emailed Kindle's support and let them know that their page is broken!
