### ISSUE TITLE
Compatibility for Kindle Mexico

### ISSUE THREAD

**Issue by fgromo** [TristanH/bookcision#15]
Hi there,

This is a great tool; I've been using it for a while now. However, my highlights have recently been relocated to the following domain: leer.amazon.com.mx/notebook, and the script does not run for me anymore. I can't even visualize my highlights on the previous website.

Is there a way you could include this new domain to keep using this fantastic tool?

Thanks a lot.

**Comment by TristanH** [comment]
Hey @fgromo , sorry for the slow response...

Amazon uses completely different names for everything when the language is switched, so it's a bit tricker than just adding the additional domain name.

_However_, it's really easy to get access to read.amazon.com/notebook even as a spanish user. Just:
* Go to amazon.com
* Hit the flag in the top right, then change your amazon.com language to English

After the above, you should be able to use bookcision at read.amazon.com/notebook (but let me know if not!)
