### ISSUE TITLE
Doesn't work with French Amazon

### ISSUE THREAD

**Issue by Rosablanche** [TristanH/bookcision#16]
Hi team,
bookcision doesn't work with the French version of Amazon wich doesn't start with read.xxx Instead the address is https://lire.amazon.fr/notebook.
You get an error message saying "Go to read.amazon.com/notebook (or read.amazon.co.jp, read.amazon.co.uk, etc.) to start.".

Is there any way to fix that ?

Cheers !

**Comment by TristanH** [comment]
Hey @Rosablanche ! Can you try the instructions here: 

https://github.com/TristanH/bookcision/issues/15#issuecomment-768002990

(not a perfect solution, but should work to get your highlights accessible!)
