### ISSUE TITLE
Partial highlights From Book

### ISSUE THREAD

**Issue by mrlad** [TristanH/bookcision#20]
I have a book with 1000+ highlights in it.  Around bookmark 915, Amazon reports that every highlight is  hidden/truncated by export restrictions.

Book decision is normally able to render highlights that Amazon won't display, but starting from this point in the book, Book decision is unable to show these highlights either. They do show highlighted in the cloud reader though.

**Comment by TristanH** [comment]
Unfortunately this is a limit enforced by Amazon (and the book publishers) that is unavoidable as far as I know.

Bookcision has never been able to get around these limits (unless you delete some of your highlights), and I've never seen anything else that can.
