### ISSUE TITLE
Can't run `grunt test` out of the box

### ISSUE THREAD

**Issue by Arthaey** [TristanH/bookcision#4]
**Repo steps:**
1. git clone repo
2. npm install
3. grunt test

**Expected:** test results

**Observed:**

```
>> Local Npm module "grunt-cli" not found. Is it installed?
Loading "webpack-dev-server.js" tasks...ERROR
```

**Solution:**
Upgrading `webpack-dev-server` via `npm install --save webpack-dev-server` seems to solve the error.

**Comment by Arthaey** [comment]
See pull request #5.

**Comment by TristanH** [comment]
Thanks for catching this! Admittedly, I did first play around and likely ran the above without noticing when first setting up my local copy, and never retraced the step.
